[toolchain]
channel = "stable" #"nightly"
components = [ "rust-src", "rust-analyzer", "clippy", "miri", "llvm-tools", "rust-docs-json" ]
targets = [
    "wasm32-unknown-unknown",
    "wasm32-wasi",
    "wasm32-wasi-preview1-threads",
    "x86_64-unknown-linux-gnu",
  ]
profile = "default"
